### ISSUE TITLE
Seems like we have a typo...

### ISSUE THREAD

**Issue by mbardoe** [Choate-Robotics/7407-DriveCode-ChargedUp#34]
https://github.com/Choate-Robotics/7407-DriveCode-ChargedUp/blob/ab9e7f98726d304042b7958114ded7b1337ff3a5/command/drivetrain.py#L92

I don't understand why line 92 says dx and not dy...

**Comment by Inspirol** [comment]
thanks for the heads up, ill make the change now to not forget it

**Comment by Inspirol** [comment]
fixed. Thanks again!
